"""Seed studios served by the read endpoints.

These mirror the Flutter mock (`bio`, `mbr`) so the app renders identically when
it switches from the in-memory repository to the API — same ids, same shape.
This is the stand-in until studios are created by users and their topics /
flashcards / quizzes are generated by the RAG pipeline from uploaded documents.
"""

from __future__ import annotations

from datetime import datetime, timezone

from .dto import (
    FlashcardDTO,
    FlashcardStatus,
    FlashcardType,
    QuizQuestionDTO,
    QuizType,
    SourceFileDTO,
    SourceFileType,
    SourceReferenceDTO,
    StudioDTO,
    TopicDTO,
)

_NOW = datetime(2026, 7, 20, tzinfo=timezone.utc)


def _bio() -> StudioDTO:
    dna = TopicDTO(
        id="bio_dna",
        studio_id="bio",
        title="DNA Replication",
        subject="Biology",
        definition="The process by which a cell copies its DNA before division, "
        "producing two identical double helices.",
        simple_explanation="DNA unzips and each strand is used as a template to "
        "build a new matching strand — you end with two copies.",
        detailed_explanation="Helicase unwinds the double helix at the origin; "
        "primase lays RNA primers; DNA polymerase III extends 5'→3', continuous "
        "on the leading strand and in Okazaki fragments on the lagging strand; "
        "ligase seals the nicks. It is semi-conservative — each daughter helix "
        "keeps one parental strand.",
        why_it_matters="It guarantees genetic continuity; errors here underlie "
        "mutations and many diseases — a classic midterm topic.",
        examples=[
            "Leading strand synthesized continuously toward the fork.",
            "Lagging strand built as Okazaki fragments joined by ligase.",
        ],
        common_mistakes=[
            "Confusing helicase (unwinds) with polymerase (extends).",
            "Forgetting DNA polymerase only works 5'→3'.",
        ],
        related_topic_ids=["bio_meiosis"],
        memory_hooks=["'Semi-conservative' = each new helix keeps one old strand."],
        sources=[
            SourceReferenceDTO(
                file_name="Lecture 5 - Molecular Biology.pdf",
                snippet="DNA replication is semi-conservative…",
                page=12,
            )
        ],
        flashcards=[
            FlashcardDTO(
                id="bio_dna_fc1",
                topic_id="bio_dna",
                front="What enzyme unwinds the DNA double helix?",
                back="Helicase.",
                type=FlashcardType.definition,
                status=FlashcardStatus.review,
            ),
            FlashcardDTO(
                id="bio_dna_fc2",
                topic_id="bio_dna",
                front="What are Okazaki fragments?",
                back="Short DNA segments synthesized discontinuously on the "
                "lagging strand, later joined by ligase.",
                type=FlashcardType.process,
                status=FlashcardStatus.learning,
            ),
            FlashcardDTO(
                id="bio_dna_fc3",
                topic_id="bio_dna",
                front="Replication is described as…",
                back="Semi-conservative.",
                type=FlashcardType.definition,
                status=FlashcardStatus.fresh,
            ),
        ],
        quiz_questions=[
            QuizQuestionDTO(
                id="bio_dna_q1",
                topic_id="bio_dna",
                type=QuizType.multipleChoice,
                question="Which enzyme joins Okazaki fragments?",
                choices=["Helicase", "Primase", "DNA ligase", "Topoisomerase"],
                answer="DNA ligase",
                explanation="Ligase seals the nicks between adjacent fragments.",
            ),
            QuizQuestionDTO(
                id="bio_dna_q2",
                topic_id="bio_dna",
                type=QuizType.trueFalse,
                question="DNA polymerase can synthesize in the 3'→5' direction.",
                choices=["True", "False"],
                answer="False",
                explanation="Polymerase only extends 5'→3'.",
            ),
        ],
        difficulty=4,
        importance=5,
        estimated_study_time_minutes=18,
        mastery=0.72,
    )

    meiosis = TopicDTO(
        id="bio_meiosis",
        studio_id="bio",
        title="Meiosis",
        subject="Biology",
        definition="A two-stage division producing four genetically distinct "
        "haploid gametes from one diploid cell.",
        simple_explanation="One cell divides twice to make four cells, each with "
        "half the chromosomes and a shuffled mix of genes.",
        detailed_explanation="Meiosis I separates homologous chromosomes "
        "(reductional); crossing over in prophase I and independent assortment "
        "create variation. Meiosis II separates sister chromatids (equational).",
        why_it_matters="Source of genetic diversity and correct chromosome number "
        "in sexual reproduction.",
        examples=["Crossing over at chiasmata.", "Independent assortment of homologs."],
        common_mistakes=["Mixing up meiosis I vs II separations."],
        related_topic_ids=["bio_dna"],
        flashcards=[
            FlashcardDTO(
                id="bio_mei_fc1",
                topic_id="bio_meiosis",
                front="How many daughter cells does meiosis produce?",
                back="Four haploid cells.",
                status=FlashcardStatus.learning,
            ),
        ],
        quiz_questions=[
            QuizQuestionDTO(
                id="bio_mei_q1",
                topic_id="bio_meiosis",
                type=QuizType.multipleChoice,
                question="Homologous chromosomes separate during…",
                choices=["Meiosis I", "Meiosis II", "Mitosis", "S phase"],
                answer="Meiosis I",
                explanation="Meiosis I is the reductional division.",
            ),
        ],
        difficulty=3,
        importance=4,
        estimated_study_time_minutes=14,
        mastery=0.55,
    )

    return StudioDTO(
        id="bio",
        title="Biology Midterm Studio",
        subject="Biology",
        created_at=_NOW,
        updated_at=_NOW,
        last_studied=_NOW,
        source_files=[
            SourceFileDTO(
                id="bio_src1",
                name="Lecture 5 - Molecular Biology.pdf",
                type=SourceFileType.pdf,
            ),
        ],
        topics=[dna, meiosis],
    )


def _mbr() -> StudioDTO:
    ahl = TopicDTO(
        id="mbr_ahl",
        studio_id="mbr",
        title="Automated Handling Lines",
        subject="Baggage Handling",
        definition="Conveyor and sortation systems that route bags from check-in "
        "to the correct make-up carousel with minimal manual handling.",
        simple_explanation="Machines move and sort bags to the right flight "
        "automatically using barcode/RFID tags.",
        detailed_explanation="Bags are inducted, scanned, screened, then diverted "
        "by tilt-tray or cross-belt sorters to make-up positions. Redundancy and "
        "fallback manual encoding handle no-reads.",
        why_it_matters="Throughput and mishandling rates are core operational KPIs.",
        examples=["Cross-belt sorter diverts to make-up carousel 7."],
        common_mistakes=["Assuming a no-read bag is lost — it goes to manual encode."],
        flashcards=[
            FlashcardDTO(
                id="mbr_ahl_fc1",
                topic_id="mbr_ahl",
                front="What handles a barcode no-read?",
                back="Manual encoding station.",
                status=FlashcardStatus.fresh,
            ),
        ],
        quiz_questions=[
            QuizQuestionDTO(
                id="mbr_ahl_q1",
                topic_id="mbr_ahl",
                type=QuizType.trueFalse,
                question="Cross-belt sorters can divert bags to multiple outputs.",
                choices=["True", "False"],
                answer="True",
                explanation="They are high-capacity multi-output sorters.",
            ),
        ],
        difficulty=2,
        importance=4,
        estimated_study_time_minutes=12,
        mastery=0.80,
    )

    return StudioDTO(
        id="mbr",
        title="MBR Training Studio",
        subject="Baggage Handling",
        created_at=_NOW,
        updated_at=_NOW,
        last_studied=_NOW,
        source_files=[
            SourceFileDTO(id="mbr_src1", name="MBR Ops Manual.pdf", type=SourceFileType.pdf),
        ],
        topics=[ahl],
    )


def seed_studios() -> dict[str, StudioDTO]:
    return {s.id: s for s in (_bio(), _mbr())}
